
export interface PayloadDeviceDataV2 {
  readonly deviceId: string
  readonly type?: string
  readonly name?: string
  readonly appType?: string
}

export enum PayloadLoginTypeV2 {
  Google = 'Google',
  Facebook = 'Facebook',
  Autogenerated = 'Autogenerated',
  Email = 'Email',
}

export type PayloadUserV2 = PayloadFacebookUserDetailsV2 | PayloadGoogleUserDetailsV2 | PayloadEmailUserDetailsV2


interface PayloadUserDetailsBaseV2<T extends PayloadLoginTypeV2> {
  readonly type: T
}

interface PayloadLoggedInUserDetailsBaseV2<T extends PayloadLoginTypeV2> extends PayloadUserDetailsBaseV2<T> {
  readonly email: string
  readonly device?: PayloadDeviceDataV2
  readonly firstName: string
  readonly lastName: string
  readonly locale: string
  readonly profileUrl: string
}

export interface PayloadFacebookUserDetailsV2 extends PayloadLoggedInUserDetailsBaseV2<PayloadLoginTypeV2.Facebook> {
  readonly facebookId: string
  readonly gender: string
}

export interface PayloadGoogleUserDetailsV2 extends PayloadLoggedInUserDetailsBaseV2<PayloadLoginTypeV2.Google> {
}

export interface PayloadEmailUserDetailsV2 extends PayloadLoggedInUserDetailsBaseV2<PayloadLoginTypeV2.Email> {
}
